# @package _group_

general:
  model_name: '${now:%y-%m-%d_%H-%M-%S}'
  device: 'cuda:0'
  save_last_state: True
  save_best_state: True
  metrics_comparison_mode: 'max'
paths:
  proj_root: '/home/iilegeza/projects/proj/'
  tboard_path: '${run_params.paths.proj_root}runs/tboard_logs/'
  hparam_path: '${run_params.paths.proj_root}runs/hparam_logs/'
  models_path: '${run_params.paths.proj_root}runs/models/'
find_lr:
  is_flr: False
  is_flr_only: False
  apply_optim_borders_flag: False
  kwargs:
    out_mode: 'save'
    logs_path: 'runs/find_lr'
dataset:
  num_workers: 2