# @package _group_

general:
  proj_name: 'PROJ_NAME'
  model_name: '${now:%y-%m-%d_%H-%M-%S}'
  device: 'cuda'
  save_last_state: True
  save_best_state: True
  metrics_comparison_mode: 'max'
paths:
  proj_root: '/home/iilegeza/projects/${run_params.general.proj_name}/'
  tboard_path: '${run_params.paths.proj_root}runs/tboard_logs/'
  hparam_path: '${run_params.paths.proj_root}runs/hparam_logs/'
  models_path: '${run_params.paths.proj_root}runs/models/'
find_lr:
  is_flr: True
  is_flr_only: True
  apply_optim_borders_flag: False
  kwargs:
    out_mode: 'save'
    logs_path: '${run_params.paths.proj_root}runs/find_lr'
dataset:
  num_workers: 2