branches:
  - name: release
  - name: master
    prerelease: preview
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/exec'
    - prepareCmd: >
        python ./release/update_version.py -f ./pyproject.toml -v ${nextRelease.version}
        && python ./release/update_version.py -f ./trainkit/__init__.py -v ${nextRelease.version}
        && $HOME/.local/bin/poetry build -f wheel
  - - '@semantic-release/git'
    - assets: [CHANGELOG.md, pyproject.toml, trainkit/__init__.py]
  - - '@semantic-release/github'
    - assets: ['dist/*.whl']
preset: conventionalcommits
