run_params:
  paths:
    proj_root: '/home/iilegeza/projects/rsna_pulmonary_embolism'
    ## all other path must be relative to proj_root
    tboard_path: 'runs/tboard_logs'
    hparam_path: 'runs/hparam_logs'
    models_path: 'runs/models'
  general:
    model_name: 'dttm'
    device: 'cuda:0'
    save_last_state: True
    save_best_state: True
    libs_threads: 2
    metrics_comparison_mode: 'max'
  find_lr:
    is_flr: False
    is_flr_only: False
    apply_optim_borders_flag: False
    kwargs:
      out_mode: 'save'
      logs_path: 'runs/find_lr'
  dataset:
    train_info_csv_path: 'data/mod/rand_study_split_label_pe_train_sample.csv'
    val_info_csv_path: 'data/mod/rand_study_split_label_pe_val_sample.csv'
    data_dir_path: 'data/mod/128x128'
    num_workers: 2
    file_ext: 'png'

hyper_params:
  general:
    num_epochs: 2
    pos_weight: 17.497
  optimizer:
    name: 'adamw'
    kwargs:
      lr: 3.0e-4
      weight_decay: 1.0e-3
  #      momentum: 0
  lr_scheduler:
    name: 'rop'
    kwargs:
      min_lr: 3.0e-4
      max_lr: 3.0e-4
      # rop kwargs
      mode: 'min'
      factor: 0.5
      threshold: 1.0e-3
      threshold_mode: 'rel'
      patience: 4
      cooldown: 3
      # clr kwargs
#      clr_step_size_up: 2
#      clr_step_size_down: 2
#      mode: 'triangular2'
#      cycle_momentum: False
      # one_cycle kwargs
#      step_frac_up: 0.3
#      step_frac_down: 0.6
#      init_lr_div_factor: 20
#      min_lr_div_factor: 1000
  dataset:
    batch_size: 2048
    mean: [0.449, 0.449, 0.449]
    std: [0.226, 0.226, 0.226]
  extra: {}
