defaults:
  - run_params: default
  - hyper_params/lr_scheduler: none
#  - override hydra/launcher: rq
#  - run_params/enqueue: rq_plugin

hydra:
  run:
    dir: '${run_params.paths.proj_root}runs/hydra/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}'
  sweep:
    dir: '${run_params.paths.proj_root}runs/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}'
