name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ~3.8

    - name: Install build deps
      run: |
        python -m pip install -U pip
        pip install --progress-bar off build

    - name: Install sematinc-release plugins
      run: >
        npm install
        @semantic-release/changelog
        @semantic-release/exec
        @semantic-release/git
        conventional-changelog-conventionalcommits
        --no-save

    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # used by github plugin
        GITHUB_TOKEN: ${{ secrets.PUSH_RELEASE_TOKEN }}  # used by git plugin
      run: npx semantic-release
