name: Tests

on: [push, pull_request]
#  pull_request:
#    branches:
#      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    # Not intended for forks.
#    if: github.repository == 'optuna/optuna'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ~3.8

    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools

    - name: Install PyTorch (CPU only)
      run : >
        pip install torch==1.9.0+cpu torchvision==0.10.0+cpu
        -f https://download.pytorch.org/whl/torch_stable.html

    - name: Install package
      run: pip install --progress-bar off ./

    - name: Run PyTest
      run: pytest